### ISSUE TITLE
hard brake action results in absurd accelerations

### ISSUE THREAD

**Issue by cho3** [zsunberg/Multilane.jl#10]
Got something like -20.45 m/s2 >> the physical limit of ~ -10m/s2

**Comment by zsunberg** [comment]
Can you post code to recreate this instance (i.e. the code to create the mdp and the state before it happens) so that I can investigate?

**Comment by cho3** [comment]
```
nb_lanes = 4
pp = PhysicalParam(nb_lanes,lane_length=100.) #2.=>col_length=8
_discount = 1.
nb_cars=10

rmodel = NoCrashRewardModel()

dmodel = NoCrashIDMMOBILModel(nb_cars, pp)

mdp = NoCrashMDP(dmodel, rmodel, _discount);

s = Multilane.MLState(false,[Multilane.CarState(50.0,2.0,30.75,0.0,Nullable{Multilane.BehaviorModel}()),Multilane.CarState(15.556523229533408,2.0,30.05188403582538,0.0,Nullable(Multilane.IDMMOBILBehavior(Multilane.IDMParam(2.0,2.0,0.8,35.0,4.0,4.0),Multilane.MOBILParam(0.0,4.0,0.2),1.0,9))),Multilane.CarState(11.731688118421243,3.0,28.82003733720375,0.0,Nullable(Multilane.IDMMOBILBehavior(Multilane.IDMParam(2.0,2.0,0.8,31.0,4.0,4.0),Multilane.MOBILParam(0.0,4.0,0.2),1.0,6))),Multilane.CarState(95.99937066040071,4.0,34.79951750438517,0.0,Nullable(Multilane.IDMMOBILBehavior(Multilane.IDMParam(2.0,2.0,0.8,35.0,4.0,4.0),Multilane.MOBILParam(0.0,4.0,0.2),1.0,9))),Multilane.CarState(61.10626061279155,1.5,33.67313781502119,0.6666666666666666,Nullable(Multilane.IDMMOBILBehavior(Multilane.IDMParam(1.0,1.0,2.0,35.0,4.0,4.0),Multilane.MOBILParam(0.5,4.0,0.2),1.0,7))),Multilane.CarState(0.3295300827715337,1.0,31.628746887390765,0.0,Nullable(Multilane.IDMMOBILBehavior(Multilane.IDMParam(1.5,1.5,1.4,35.0,4.0,4.0),Multilane.MOBILParam(0.25,4.0,0.2),1.0,8))),Multilane.CarState(0.0,3.0,30.75,0.0,Nullable(Multilane.IDMMOBILBehavior(Multilane.IDMParam(1.5,1.5,1.4,35.0,4.0,4.0),Multilane.MOBILParam(0.25,4.0,0.2),1.0,8)))])
```

This should give an e-brake acceleration of -16.4101 if you call actions()

**Comment by zsunberg** [comment]
That is the intended behavior (maybe we should talk about whether the intention is reasonable). The other car cut the ego vehicle off leaving only a 10 meter gap. 16 m/s^2 is the braking that you would need to apply if the car in front of you slammed on his brakes at the physical limit.

The physical limit is in mdp.dmodel.phys_param.brake_limit, and it is 20 by default. When you mentioned that the physical limit is 10, which variable were you thinking I was using?

Maybe this braking is too conservative? Also, a smaller time step would make us have to brake less hard (in this case the time step sort of corresponds to reaction time)

**Comment by cho3** [comment]
Ok cool, this was just something weird I was seeing in visualization then. I also didn't see any crazy changes in position, so it looks like this is a nonissue.
